version: 2.1

jobs:
  build-and-test:
    machine:
      image: ubuntu-2004:current

    steps:
      - checkout
      - run: make deps
      # Dodane uruchomienie lintera przed testami (Zadanie, punkt 9)
      - run:
          name: Run Linter
          command: make lint
      - run: make test
      - run:
          name: Build Docker image
          command: make docker_build

workflows:
  basic:
    jobs:
      - build-and-test