version: 2.1

jobs:
  build-and-test:
    machine:
      image: ubuntu-2004:current

    steps:
      - checkout
      - run: make deps
      - run:
          name: Run Linter
          command: make lint
      - run: make test
      - setup_remote_docker
      - run:
          name: Build and push Docker image
          environment:
            # Tutaj mapujemy zmienne z CircleCI Settings do zmiennych używanych przez Makefile
            USERNAME: $DOCKER_USER
            DOCKER_PASSWORD: $DOCKER_PASSWORD
          command: make docker_push

workflows:
  basic:
    jobs:
      - build-and-test