version: 2.1

jobs:
  build-and-test:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - run: make deps
      - run: make lint
      - run: make test
      - setup_remote_docker
      - run:
          name: Build and push Docker image
          command: make docker_push

workflows:
  version: 2
  basic:
    jobs:
      - build-and-test